import { Metadata } from "next";
import StyledComponentsRegistry from "@/lib/registry";
import GlobalStateProvider from "./GlobalStateProvider/GlobalStateProvider";
import QueryProvider from "@/react-query/QueryProvider";
import { cookies } from "next/headers";
import PrivatRoutes from "@/components/PrivatRoutes/PrivatRoutes";

export const metadata: Metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

interface IUser {
  email?: string;
  firstName?: string;
  balance?: number;
  message?: string;
}

const BASE_URL = "https://wallet-backend-xmk0.onrender.com/api";
const USER_CURRENT = "/users/current";

async function RootLayout({ children }: { children: React.ReactNode }) {
  const cookieStore = cookies();
  const authToken = cookieStore.get("authToken")?.value;

  const options = {
    method: "GET",
    headers: {
      Authorization: `Bearer ${authToken}`,
    },
  };

  const resFetch = await fetch(`${BASE_URL}${USER_CURRENT}`, options);
  const user = (await resFetch.json()) as IUser;

  const isLoggedIn = !user?.email;

  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/vercel.svg" />
      </head>
      <body>
        <h1>ROOT LAYOUT</h1>
        <GlobalStateProvider user={user} isLoggedIn={isLoggedIn}>
          <QueryProvider>
            <StyledComponentsRegistry>
              {/* <PrivatRoutes isLoggedIn={isLoggedIn}> */}
                {children}
                {/* </PrivatRoutes> */}
            </StyledComponentsRegistry>
          </QueryProvider>
        </GlobalStateProvider>
      </body>
    </html>
  );
}

export default RootLayout;
// export default wrapper.withRedux(RootLayout);
